### ISSUE TITLE
Code for SDK 4?

### ISSUE THREAD

**Issue by sibbl** [heqian/home-butler#1]
I'm a huge fan of the app but it stopped working on my Fitbit Ionic quite a while ago.
I'd be interested in forking and fixing it. However, the current code is SDK 5 only.

Is there any SDK 4 code available on GitHub? The git history doesn't give me much unfortunately. I'd be happy to have something to build on.

Thanks in advance!

**Comment by heqian** [comment]
There is a branch called `legacy`. It's for SDK4. :)
